### ISSUE TITLE
VSCode extension now is called with `reditorsupport.r`, not `njpwerner.reditorsupport.r`

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/images-datascience#97]
The VSCode extension for R is not present in the VSCode services available on SSP Cloud.
I think that this is due to the command used to install it. The following does not work:
```bash
code-server --install-extension njpwerner.reditorsupport.r
```
The following works:
```bash
code-server --install-extension reditorsupport.r
```

**Comment by avouacr** [comment]
Thank's @fBedecarrats, it's fixed in 6e47e15e8731dc96f5254a7a3e5aac6180582f33

**Comment by fBedecarrats** [comment]
Sorry @avouacr  but the catalogue image for `Vscode-r-python-julia` is launched without the R extension, even when I set Service/PullPolicy/Always. Is there something to do to ensure that the fix gets into the SSPCloud catalogue image?
Thanks!

**Comment by avouacr** [comment]
HI @fBedecarrats, indeed, I didn't put the new image in prod, it should be good now. Can you test and confirm ?

**Comment by fBedecarrats** [comment]
Salut @avouacr! The extension is now available, thanks!
Some required packages are still missing for the minimal R to work out of the box. I created a PR to add it (#101).
